//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitymodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KKGEntities : DbContext
    {
        public KKGEntities()
            : base("name=KKGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int USP_BIND_PROCTUCTIONORDER(string p_DEPOTID, string p_FINYEAR)
        {
            var p_DEPOTIDParameter = p_DEPOTID != null ?
                new ObjectParameter("P_DEPOTID", p_DEPOTID) :
                new ObjectParameter("P_DEPOTID", typeof(string));
    
            var p_FINYEARParameter = p_FINYEAR != null ?
                new ObjectParameter("P_FINYEAR", p_FINYEAR) :
                new ObjectParameter("P_FINYEAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_BIND_PROCTUCTIONORDER", p_DEPOTIDParameter, p_FINYEARParameter);
        }
    
        public virtual ObjectResult<USP_BIND_VENDOR_AND_CURRENCY_Result> USP_BIND_VENDOR_AND_CURRENCY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BIND_VENDOR_AND_CURRENCY_Result>("USP_BIND_VENDOR_AND_CURRENCY");
        }
    
        public virtual ObjectResult<USP_BIND_PACKSIZE_MRP_AND_RATE_Result> USP_BIND_PACKSIZE_MRP_AND_RATE(string p_PRODUCTID, string p_TPUID, string p_FROMDATE)
        {
            var p_PRODUCTIDParameter = p_PRODUCTID != null ?
                new ObjectParameter("P_PRODUCTID", p_PRODUCTID) :
                new ObjectParameter("P_PRODUCTID", typeof(string));
    
            var p_TPUIDParameter = p_TPUID != null ?
                new ObjectParameter("P_TPUID", p_TPUID) :
                new ObjectParameter("P_TPUID", typeof(string));
    
            var p_FROMDATEParameter = p_FROMDATE != null ?
                new ObjectParameter("P_FROMDATE", p_FROMDATE) :
                new ObjectParameter("P_FROMDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BIND_PACKSIZE_MRP_AND_RATE_Result>("USP_BIND_PACKSIZE_MRP_AND_RATE", p_PRODUCTIDParameter, p_TPUIDParameter, p_FROMDATEParameter);
        }
    
        public virtual ObjectResult<USP_BIND_TODEPOT_Result> USP_BIND_TODEPOT(string p_DEPOID)
        {
            var p_DEPOIDParameter = p_DEPOID != null ?
                new ObjectParameter("P_DEPOID", p_DEPOID) :
                new ObjectParameter("P_DEPOID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BIND_TODEPOT_Result>("USP_BIND_TODEPOT", p_DEPOIDParameter);
        }
    
        public virtual ObjectResult<USP_FETCH_RECENT_TXN_TRANSPORTER_FAC_Result> USP_FETCH_RECENT_TXN_TRANSPORTER_FAC(string p_FROMDEPOT, string p_TODEPOT, string p_FINYEAR, string p_MODULEID)
        {
            var p_FROMDEPOTParameter = p_FROMDEPOT != null ?
                new ObjectParameter("P_FROMDEPOT", p_FROMDEPOT) :
                new ObjectParameter("P_FROMDEPOT", typeof(string));
    
            var p_TODEPOTParameter = p_TODEPOT != null ?
                new ObjectParameter("P_TODEPOT", p_TODEPOT) :
                new ObjectParameter("P_TODEPOT", typeof(string));
    
            var p_FINYEARParameter = p_FINYEAR != null ?
                new ObjectParameter("P_FINYEAR", p_FINYEAR) :
                new ObjectParameter("P_FINYEAR", typeof(string));
    
            var p_MODULEIDParameter = p_MODULEID != null ?
                new ObjectParameter("P_MODULEID", p_MODULEID) :
                new ObjectParameter("P_MODULEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_FETCH_RECENT_TXN_TRANSPORTER_FAC_Result>("USP_FETCH_RECENT_TXN_TRANSPORTER_FAC", p_FROMDEPOTParameter, p_TODEPOTParameter, p_FINYEARParameter, p_MODULEIDParameter);
        }
    
        public virtual ObjectResult<USP_GET_TRANSPORTER_BASED_ON_DEPOT_Result> USP_GET_TRANSPORTER_BASED_ON_DEPOT(string p_DEPOTID, string p_TXNID)
        {
            var p_DEPOTIDParameter = p_DEPOTID != null ?
                new ObjectParameter("P_DEPOTID", p_DEPOTID) :
                new ObjectParameter("P_DEPOTID", typeof(string));
    
            var p_TXNIDParameter = p_TXNID != null ?
                new ObjectParameter("P_TXNID", p_TXNID) :
                new ObjectParameter("P_TXNID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_TRANSPORTER_BASED_ON_DEPOT_Result>("USP_GET_TRANSPORTER_BASED_ON_DEPOT", p_DEPOTIDParameter, p_TXNIDParameter);
        }
    }
}
