//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsEntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccountsEntities : DbContext
    {
        public AccountsEntities()
            : base("name=AccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<USP_ACC_COSTCWENTRE_GET_Result> USP_ACC_COSTCWENTRE_GET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_COSTCWENTRE_GET_Result>("USP_ACC_COSTCWENTRE_GET");
        }
    
        public virtual ObjectResult<USP_GET_BUSINESSSEGMENT_LIST_Result> USP_GET_BUSINESSSEGMENT_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_BUSINESSSEGMENT_LIST_Result>("USP_GET_BUSINESSSEGMENT_LIST");
        }
    
        public virtual ObjectResult<USP_DEPARTMENT_SHOW_Result> USP_DEPARTMENT_SHOW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DEPARTMENT_SHOW_Result>("USP_DEPARTMENT_SHOW");
        }
    
        public virtual ObjectResult<SP_DIVISION_SHOW_Result> SP_DIVISION_SHOW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DIVISION_SHOW_Result>("SP_DIVISION_SHOW");
        }
    
        public virtual ObjectResult<USP_ACC_VOUCHERTYPES_GET_Result> USP_ACC_VOUCHERTYPES_GET(string vOUCHERTYPEID, string tYPE, string rEGIOIUNID)
        {
            var vOUCHERTYPEIDParameter = vOUCHERTYPEID != null ?
                new ObjectParameter("VOUCHERTYPEID", vOUCHERTYPEID) :
                new ObjectParameter("VOUCHERTYPEID", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var rEGIOIUNIDParameter = rEGIOIUNID != null ?
                new ObjectParameter("REGIOIUNID", rEGIOIUNID) :
                new ObjectParameter("REGIOIUNID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_VOUCHERTYPES_GET_Result>("USP_ACC_VOUCHERTYPES_GET", vOUCHERTYPEIDParameter, tYPEParameter, rEGIOIUNIDParameter);
        }
    
        public virtual ObjectResult<USP_ACC_PAYMENT_TYPE_GET_Result> USP_ACC_PAYMENT_TYPE_GET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_PAYMENT_TYPE_GET_Result>("USP_ACC_PAYMENT_TYPE_GET");
        }
    
        public virtual ObjectResult<SP_CATEWGORY_SHOW_Result> SP_CATEWGORY_SHOW(string p_CUSTOMERID)
        {
            var p_CUSTOMERIDParameter = p_CUSTOMERID != null ?
                new ObjectParameter("P_CUSTOMERID", p_CUSTOMERID) :
                new ObjectParameter("P_CUSTOMERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CATEWGORY_SHOW_Result>("SP_CATEWGORY_SHOW", p_CUSTOMERIDParameter);
        }
    
        public virtual ObjectResult<USP_STATE_SHOW_Result> USP_STATE_SHOW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_STATE_SHOW_Result>("USP_STATE_SHOW");
        }
    
        public virtual ObjectResult<USP_ACC_THIRDPARTYVENDOR_GET_Result> USP_ACC_THIRDPARTYVENDOR_GET(string aCCCODE)
        {
            var aCCCODEParameter = aCCCODE != null ?
                new ObjectParameter("ACCCODE", aCCCODE) :
                new ObjectParameter("ACCCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_THIRDPARTYVENDOR_GET_Result>("USP_ACC_THIRDPARTYVENDOR_GET", aCCCODEParameter);
        }
    
        public virtual ObjectResult<USP_ACC_ACCOUNTGROUPTYPEGET_Result> USP_ACC_ACCOUNTGROUPTYPEGET(Nullable<int> p_ID, string p_NAME, Nullable<int> p_SEQUENCE)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SEQUENCEParameter = p_SEQUENCE.HasValue ?
                new ObjectParameter("p_SEQUENCE", p_SEQUENCE) :
                new ObjectParameter("p_SEQUENCE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_ACCOUNTGROUPTYPEGET_Result>("USP_ACC_ACCOUNTGROUPTYPEGET", p_IDParameter, p_NAMEParameter, p_SEQUENCEParameter);
        }
    
        public virtual ObjectResult<USP_ACC_VOUCHERTYPEACC_GET_Result> USP_ACC_VOUCHERTYPEACC_GET(string vOUCHERTYPEID, string tYPE, string rEGIOIUNID)
        {
            var vOUCHERTYPEIDParameter = vOUCHERTYPEID != null ?
                new ObjectParameter("VOUCHERTYPEID", vOUCHERTYPEID) :
                new ObjectParameter("VOUCHERTYPEID", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var rEGIOIUNIDParameter = rEGIOIUNID != null ?
                new ObjectParameter("REGIOIUNID", rEGIOIUNID) :
                new ObjectParameter("REGIOIUNID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_VOUCHERTYPEACC_GET_Result>("USP_ACC_VOUCHERTYPEACC_GET", vOUCHERTYPEIDParameter, tYPEParameter, rEGIOIUNIDParameter);
        }
    
        public virtual ObjectResult<USP_REGION_SHOW_Result> USP_REGION_SHOW(string uSERTYPE, string uSERID)
        {
            var uSERTYPEParameter = uSERTYPE != null ?
                new ObjectParameter("USERTYPE", uSERTYPE) :
                new ObjectParameter("USERTYPE", typeof(string));
    
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_REGION_SHOW_Result>("USP_REGION_SHOW", uSERTYPEParameter, uSERIDParameter);
        }
    
        public virtual ObjectResult<USP_GET_GSTNO_Result> USP_GET_GSTNO(string p_PartyID, string p_StateID)
        {
            var p_PartyIDParameter = p_PartyID != null ?
                new ObjectParameter("P_PartyID", p_PartyID) :
                new ObjectParameter("P_PartyID", typeof(string));
    
            var p_StateIDParameter = p_StateID != null ?
                new ObjectParameter("P_StateID", p_StateID) :
                new ObjectParameter("P_StateID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_GSTNO_Result>("USP_GET_GSTNO", p_PartyIDParameter, p_StateIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> USP_ACC_LEDGER_OUTSTANDING(string p_LEDGERID, string p_REGIONID, string p_FRMDATE, string p_TODATE, string p_FINYEAR)
        {
            var p_LEDGERIDParameter = p_LEDGERID != null ?
                new ObjectParameter("P_LEDGERID", p_LEDGERID) :
                new ObjectParameter("P_LEDGERID", typeof(string));
    
            var p_REGIONIDParameter = p_REGIONID != null ?
                new ObjectParameter("P_REGIONID", p_REGIONID) :
                new ObjectParameter("P_REGIONID", typeof(string));
    
            var p_FRMDATEParameter = p_FRMDATE != null ?
                new ObjectParameter("P_FRMDATE", p_FRMDATE) :
                new ObjectParameter("P_FRMDATE", typeof(string));
    
            var p_TODATEParameter = p_TODATE != null ?
                new ObjectParameter("P_TODATE", p_TODATE) :
                new ObjectParameter("P_TODATE", typeof(string));
    
            var p_FINYEARParameter = p_FINYEAR != null ?
                new ObjectParameter("P_FINYEAR", p_FINYEAR) :
                new ObjectParameter("P_FINYEAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("USP_ACC_LEDGER_OUTSTANDING", p_LEDGERIDParameter, p_REGIONIDParameter, p_FRMDATEParameter, p_TODATEParameter, p_FINYEARParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_ACC_COSTCENTRE_APPLICABLE(string accountID)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_ACC_COSTCENTRE_APPLICABLE", accountIDParameter);
        }
    
        public virtual ObjectResult<string> USP_ACC_NEGATIVEBAL_CHECKING(string p_LEDGERID, string p_VOUCHERTYPEID, string p_TXNTYPEID, string p_MODE)
        {
            var p_LEDGERIDParameter = p_LEDGERID != null ?
                new ObjectParameter("P_LEDGERID", p_LEDGERID) :
                new ObjectParameter("P_LEDGERID", typeof(string));
    
            var p_VOUCHERTYPEIDParameter = p_VOUCHERTYPEID != null ?
                new ObjectParameter("P_VOUCHERTYPEID", p_VOUCHERTYPEID) :
                new ObjectParameter("P_VOUCHERTYPEID", typeof(string));
    
            var p_TXNTYPEIDParameter = p_TXNTYPEID != null ?
                new ObjectParameter("P_TXNTYPEID", p_TXNTYPEID) :
                new ObjectParameter("P_TXNTYPEID", typeof(string));
    
            var p_MODEParameter = p_MODE != null ?
                new ObjectParameter("P_MODE", p_MODE) :
                new ObjectParameter("P_MODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_ACC_NEGATIVEBAL_CHECKING", p_LEDGERIDParameter, p_VOUCHERTYPEIDParameter, p_TXNTYPEIDParameter, p_MODEParameter);
        }
    
        public virtual ObjectResult<SP_Get_Department_Component_Result> SP_Get_Department_Component(string p_DeptID)
        {
            var p_DeptIDParameter = p_DeptID != null ?
                new ObjectParameter("P_DeptID", p_DeptID) :
                new ObjectParameter("P_DeptID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Department_Component_Result>("SP_Get_Department_Component", p_DeptIDParameter);
        }
    
        public virtual ObjectResult<SP_FILL_SUBCOMPONENT_Result> SP_FILL_SUBCOMPONENT(Nullable<int> p_COMPONENTID)
        {
            var p_COMPONENTIDParameter = p_COMPONENTID.HasValue ?
                new ObjectParameter("P_COMPONENTID", p_COMPONENTID) :
                new ObjectParameter("P_COMPONENTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FILL_SUBCOMPONENT_Result>("SP_FILL_SUBCOMPONENT", p_COMPONENTIDParameter);
        }
    
        public virtual ObjectResult<USP_ACC_TAXAPPLICALE_TDS_Result> USP_ACC_TAXAPPLICALE_TDS(string p_LEDGERID, string p_VOUCHERDATE, string p_FINYEAR, Nullable<decimal> p_AMOUNT, string p_BRANCHID, string p_VOUCHERTYPEID, string p_DrCr, Nullable<decimal> p_CalAmt)
        {
            var p_LEDGERIDParameter = p_LEDGERID != null ?
                new ObjectParameter("P_LEDGERID", p_LEDGERID) :
                new ObjectParameter("P_LEDGERID", typeof(string));
    
            var p_VOUCHERDATEParameter = p_VOUCHERDATE != null ?
                new ObjectParameter("P_VOUCHERDATE", p_VOUCHERDATE) :
                new ObjectParameter("P_VOUCHERDATE", typeof(string));
    
            var p_FINYEARParameter = p_FINYEAR != null ?
                new ObjectParameter("P_FINYEAR", p_FINYEAR) :
                new ObjectParameter("P_FINYEAR", typeof(string));
    
            var p_AMOUNTParameter = p_AMOUNT.HasValue ?
                new ObjectParameter("P_AMOUNT", p_AMOUNT) :
                new ObjectParameter("P_AMOUNT", typeof(decimal));
    
            var p_BRANCHIDParameter = p_BRANCHID != null ?
                new ObjectParameter("P_BRANCHID", p_BRANCHID) :
                new ObjectParameter("P_BRANCHID", typeof(string));
    
            var p_VOUCHERTYPEIDParameter = p_VOUCHERTYPEID != null ?
                new ObjectParameter("P_VOUCHERTYPEID", p_VOUCHERTYPEID) :
                new ObjectParameter("P_VOUCHERTYPEID", typeof(string));
    
            var p_DrCrParameter = p_DrCr != null ?
                new ObjectParameter("P_DrCr", p_DrCr) :
                new ObjectParameter("P_DrCr", typeof(string));
    
            var p_CalAmtParameter = p_CalAmt.HasValue ?
                new ObjectParameter("P_CalAmt", p_CalAmt) :
                new ObjectParameter("P_CalAmt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_TAXAPPLICALE_TDS_Result>("USP_ACC_TAXAPPLICALE_TDS", p_LEDGERIDParameter, p_VOUCHERDATEParameter, p_FINYEARParameter, p_AMOUNTParameter, p_BRANCHIDParameter, p_VOUCHERTYPEIDParameter, p_DrCrParameter, p_CalAmtParameter);
        }
    
        public virtual int SP_ACC_INVOICEDETAILS(string voucherid, string leadgerID, string voucherType, string branchID)
        {
            var voucheridParameter = voucherid != null ?
                new ObjectParameter("Voucherid", voucherid) :
                new ObjectParameter("Voucherid", typeof(string));
    
            var leadgerIDParameter = leadgerID != null ?
                new ObjectParameter("LeadgerID", leadgerID) :
                new ObjectParameter("LeadgerID", typeof(string));
    
            var voucherTypeParameter = voucherType != null ?
                new ObjectParameter("VoucherType", voucherType) :
                new ObjectParameter("VoucherType", typeof(string));
    
            var branchIDParameter = branchID != null ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACC_INVOICEDETAILS", voucheridParameter, leadgerIDParameter, voucherTypeParameter, branchIDParameter);
        }
    
        public virtual ObjectResult<USP_ACC_INVOICEDETAILS_DEBIT_CREDIT_Result> USP_ACC_INVOICEDETAILS_DEBIT_CREDIT(string voucherid, string leadgerID, string voucherType)
        {
            var voucheridParameter = voucherid != null ?
                new ObjectParameter("Voucherid", voucherid) :
                new ObjectParameter("Voucherid", typeof(string));
    
            var leadgerIDParameter = leadgerID != null ?
                new ObjectParameter("LeadgerID", leadgerID) :
                new ObjectParameter("LeadgerID", typeof(string));
    
            var voucherTypeParameter = voucherType != null ?
                new ObjectParameter("VoucherType", voucherType) :
                new ObjectParameter("VoucherType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_INVOICEDETAILS_DEBIT_CREDIT_Result>("USP_ACC_INVOICEDETAILS_DEBIT_CREDIT", voucheridParameter, leadgerIDParameter, voucherTypeParameter);
        }
    
        public virtual ObjectResult<string> SP_CHECK_EXPENSES_LEDGET(string p_LedgerID)
        {
            var p_LedgerIDParameter = p_LedgerID != null ?
                new ObjectParameter("P_LedgerID", p_LedgerID) :
                new ObjectParameter("P_LedgerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CHECK_EXPENSES_LEDGET", p_LedgerIDParameter);
        }
    
        public virtual ObjectResult<string> SP_CHECK_EXPENSES_LEDGERGET(string p_LedgerID)
        {
            var p_LedgerIDParameter = p_LedgerID != null ?
                new ObjectParameter("P_LedgerID", p_LedgerID) :
                new ObjectParameter("P_LedgerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CHECK_EXPENSES_LEDGERGET", p_LedgerIDParameter);
        }
    
        public virtual ObjectResult<SP_GET_BUDGET_GROUP_BALANCE_Result> SP_GET_BUDGET_GROUP_BALANCE(string p_LedgerID, Nullable<decimal> p_Amount, string p_VoucherDate, string p_FYEAR, string p_BudgetXml, string p_DepartmentID)
        {
            var p_LedgerIDParameter = p_LedgerID != null ?
                new ObjectParameter("P_LedgerID", p_LedgerID) :
                new ObjectParameter("P_LedgerID", typeof(string));
    
            var p_AmountParameter = p_Amount.HasValue ?
                new ObjectParameter("P_Amount", p_Amount) :
                new ObjectParameter("P_Amount", typeof(decimal));
    
            var p_VoucherDateParameter = p_VoucherDate != null ?
                new ObjectParameter("p_VoucherDate", p_VoucherDate) :
                new ObjectParameter("p_VoucherDate", typeof(string));
    
            var p_FYEARParameter = p_FYEAR != null ?
                new ObjectParameter("P_FYEAR", p_FYEAR) :
                new ObjectParameter("P_FYEAR", typeof(string));
    
            var p_BudgetXmlParameter = p_BudgetXml != null ?
                new ObjectParameter("P_BudgetXml", p_BudgetXml) :
                new ObjectParameter("P_BudgetXml", typeof(string));
    
            var p_DepartmentIDParameter = p_DepartmentID != null ?
                new ObjectParameter("P_DepartmentID", p_DepartmentID) :
                new ObjectParameter("P_DepartmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BUDGET_GROUP_BALANCE_Result>("SP_GET_BUDGET_GROUP_BALANCE", p_LedgerIDParameter, p_AmountParameter, p_VoucherDateParameter, p_FYEARParameter, p_BudgetXmlParameter, p_DepartmentIDParameter);
        }
    
        public virtual ObjectResult<string> usp_TAXACTION(string tAXID)
        {
            var tAXIDParameter = tAXID != null ?
                new ObjectParameter("TAXID", tAXID) :
                new ObjectParameter("TAXID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_TAXACTION", tAXIDParameter);
        }
    
        public virtual ObjectResult<usp_PRODUCTMADSTER_SHOW_Result> usp_PRODUCTMADSTER_SHOW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PRODUCTMADSTER_SHOW_Result>("usp_PRODUCTMADSTER_SHOW");
        }
    
        public virtual ObjectResult<USP_VOUCHER_HEADERDETAILS_Result> USP_VOUCHER_HEADERDETAILS(string p_FORMDATE, string p_TODATE, string p_USERID, string p_FINYEAR, string p_VOUCHERTYPEID, string p_CHECKER, string p_DEPOTID, string p_FROMUNLOCKVOUCHER)
        {
            var p_FORMDATEParameter = p_FORMDATE != null ?
                new ObjectParameter("p_FORMDATE", p_FORMDATE) :
                new ObjectParameter("p_FORMDATE", typeof(string));
    
            var p_TODATEParameter = p_TODATE != null ?
                new ObjectParameter("p_TODATE", p_TODATE) :
                new ObjectParameter("p_TODATE", typeof(string));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            var p_FINYEARParameter = p_FINYEAR != null ?
                new ObjectParameter("p_FINYEAR", p_FINYEAR) :
                new ObjectParameter("p_FINYEAR", typeof(string));
    
            var p_VOUCHERTYPEIDParameter = p_VOUCHERTYPEID != null ?
                new ObjectParameter("p_VOUCHERTYPEID", p_VOUCHERTYPEID) :
                new ObjectParameter("p_VOUCHERTYPEID", typeof(string));
    
            var p_CHECKERParameter = p_CHECKER != null ?
                new ObjectParameter("p_CHECKER", p_CHECKER) :
                new ObjectParameter("p_CHECKER", typeof(string));
    
            var p_DEPOTIDParameter = p_DEPOTID != null ?
                new ObjectParameter("p_DEPOTID", p_DEPOTID) :
                new ObjectParameter("p_DEPOTID", typeof(string));
    
            var p_FROMUNLOCKVOUCHERParameter = p_FROMUNLOCKVOUCHER != null ?
                new ObjectParameter("p_FROMUNLOCKVOUCHER", p_FROMUNLOCKVOUCHER) :
                new ObjectParameter("p_FROMUNLOCKVOUCHER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_VOUCHER_HEADERDETAILS_Result>("USP_VOUCHER_HEADERDETAILS", p_FORMDATEParameter, p_TODATEParameter, p_USERIDParameter, p_FINYEARParameter, p_VOUCHERTYPEIDParameter, p_CHECKERParameter, p_DEPOTIDParameter, p_FROMUNLOCKVOUCHERParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_chkdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_chkdate");
        }
    
        public virtual ObjectResult<USP_ACC_ACCOUNTGROUPTYPE_GET_Result> USP_ACC_ACCOUNTGROUPTYPE_GET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ACC_ACCOUNTGROUPTYPE_GET_Result>("USP_ACC_ACCOUNTGROUPTYPE_GET");
        }
    
        public virtual int FETCH_CHEQUEBOOKLET(string p_BANKID, string branchID)
        {
            var p_BANKIDParameter = p_BANKID != null ?
                new ObjectParameter("P_BANKID", p_BANKID) :
                new ObjectParameter("P_BANKID", typeof(string));
    
            var branchIDParameter = branchID != null ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FETCH_CHEQUEBOOKLET", p_BANKIDParameter, branchIDParameter);
        }
    
        public virtual ObjectResult<USP_GET_TAXTYPE_Result> USP_GET_TAXTYPE(string p_PartyID, string p_StateID, string p_DepoID)
        {
            var p_PartyIDParameter = p_PartyID != null ?
                new ObjectParameter("P_PartyID", p_PartyID) :
                new ObjectParameter("P_PartyID", typeof(string));
    
            var p_StateIDParameter = p_StateID != null ?
                new ObjectParameter("P_StateID", p_StateID) :
                new ObjectParameter("P_StateID", typeof(string));
    
            var p_DepoIDParameter = p_DepoID != null ?
                new ObjectParameter("P_DepoID", p_DepoID) :
                new ObjectParameter("P_DepoID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_TAXTYPE_Result>("USP_GET_TAXTYPE", p_PartyIDParameter, p_StateIDParameter, p_DepoIDParameter);
        }
    
        public virtual ObjectResult<SP_GET_TAXTYPE_NAME_Result> SP_GET_TAXTYPE_NAME(string p_TaxTypeID)
        {
            var p_TaxTypeIDParameter = p_TaxTypeID != null ?
                new ObjectParameter("P_TaxTypeID", p_TaxTypeID) :
                new ObjectParameter("P_TaxTypeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_TAXTYPE_NAME_Result>("SP_GET_TAXTYPE_NAME", p_TaxTypeIDParameter);
        }
    }
}
